src/Entity/Car.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\This;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CarRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Car
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="car")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", inversedBy="cars")
     */
    private $product;

    /**
     * @ORM\Column(type="integer")
     */
    private $Quantity;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Command", mappedBy="car")
     */
    private $commands;

    public function __construct()
    {
        $this->commands = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return Collection|Command[]
     */
    public function getCommands(): Collection
    {
        return $this->commands;
    }

    public function addCommand(Command $command): self
    {
        if (!$this->commands->contains($command)) {
            $this->commands[] = $command;
            $command->setCar($this);
        }

        return $this;
    }

    public function removeCommand(Command $command): self
    {
        if ($this->commands->contains($command)) {
            $this->commands->removeElement($command);
            // set the owning side to null (unless already changed)
            if ($command->getCar() === $this) {
                $command->setCar(null);
            }
        }

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCartPrice()
    {
        $this->price = $this->getproduct()->getPrice() * $this->getQuantity();
    }
}

templates/Administration/CategoryForm.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <!-- Bootstrap 4 css -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- css -->
    {{ encore_entry_link_tags('base') }}
{% endblock %}
{% block containt %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                {{ form(category_form) }}
            </div>
        </div>
{% endblock %}
{% block javascripts %}
    <!-- Bootstrap 4 js.File -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% endblock %}

templates/Administration/ProductForm.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <!-- Bootstrap 4 css -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- css -->
    {{ encore_entry_link_tags('base') }}
{% endblock %}
{% block containt %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                {{ form(Product_form) }}
            </div>
        </div>
{% endblock %}
{% block javascripts %}
    <!-- Bootstrap 4 js.File -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% endblock %}

templates/Administration/admin.html.twig
{% extends 'base.html.twig' %}
{% block containt %}
<h1> The admin Pages</h1>
{% endblock %}

templates/Administration/categories.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <!-- Bootstrap 4 css -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- css -->
    {{ encore_entry_link_tags('base') }}
    {{ encore_entry_link_tags('car') }}
{% endblock %}
{% block containt %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="main-box clearfix">
                    <div class="table-responsive">
                        <table class="table user-list">
                            <thead>
                            <tr>
                                <th style="width: 15px"><span>Identification</span></th>
                                <th><span>Name</span></th>
                                <th><span>Description</span></th>
                                <th><span>Create at</span></th>
                                <th style="width: 15px"><span>Available</span></th>
                                <th>&nbsp;</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for category in categories %}
                                <tr>
                                    <td>{{ category.id }}</td>
                                    <td>{{ category.name }}</td>
                                    <td>{{ category.description }}</td>
                                    <td>{{ category.created |date('d/m/y h:m:s') }}</td>
                                    <td>{{ category.available }}</td>
                                    <td style="width: 10%;">
                                        <a href="{{ path('admin_categories_update_set_inactive', {id:category.id}) }}" class="table-link danger">
                                            <span class="fa-stack">
                                                <i class="fa fa-square fa-stack-2x"></i>
                                                <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                        <a href="{{ path('admin_categories_update', {id:category.id}) }}" class="table-link success">
                                            <span class="fa-stack">
                                                <i class="fa fa-square fa-stack-2x"></i>
                                                <i class="fa fa-edit fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">
                    <div class="col-auto mr-auto"></div>
                    <div class="col-auto">
                        <a class="glyphicon glyphicon-plus btn btn-info btn-lg " href="{{ path('admin_add_category') }}"> Plus </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/Administration/products.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <!-- Bootstrap 4 css -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- css -->
    {{ encore_entry_link_tags('base') }}
    {{ encore_entry_link_tags('car') }}
{% endblock %}
{% block containt %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="main-box clearfix">
                    <div class="table-responsive">
                        <table class="table user-list">
                            <thead>
                            <tr>
                                <th><span>Images</span></th>
                                <th><span>Identification</span></th>
                                <th><span>Name</span></th>
                                <th><span>Description</span></th>
                                <th><span>Quantity</span></th>
                                <th class="text-center"><span>Unit Price </span></th>
                                <th><span>Available</span></th>
                                <th><span>Create at</span></th>
                                <th><span>Category</span></th>
                                <th>&nbsp;</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for product in products %}
                                    <tr>
                                        <td>
                                            <img src="{{ asset( product.images )}}" alt="">
                                        </td>
                                        <td>{{ product.id }}</td>
                                        <td>{{ product.name }}</td>
                                        <td>{{ product.description }}</td>
                                        <td>{{ product.quantity }}</td>
                                        <td>{{ product.price }}</td>
                                        <td>{{ product.available }}</td>
                                        <td>{{ product.created |date('d/m/y h:m:s') }}</td>
                                        <td>{{ product.category.name }}</td>
                                        <td style="width: 10%;">
                                            <a href="{{ path('admin_product_update_set_inactive', {id:product.id}) }}" class="table-link danger">
                                                <span class="fa-stack">
                                                    <i class="fa fa-square fa-stack-2x"></i>
                                                    <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </a>
                                            <a href="{{path('admin_product_update', {id:product.id} )}}" class="table-link success">
                                                <span class="fa-stack">
                                                    <i class="fa fa-square fa-stack-2x"></i>
                                                    <i class="fa fa-edit fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">
                    <div class="col-auto mr-auto">
                    </div>
                    <div class="col-auto">
                        <a class="glyphicon glyphicon-plus btn btn-info btn-lg " href="{{ path('admin_add_product') }}"> Plus </a>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}